<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AmazonLambdaCore>2.5.1</AmazonLambdaCore>
        <AmazonLambdaSerializationSystemTextJson>2.4.4</AmazonLambdaSerializationSystemTextJson>
        <AmazonCDKAWSLambdaDotNet>0.0.6</AmazonCDKAWSLambdaDotNet>
        <AmazonCDKLib>2.188.0</AmazonCDKLib>
        <AmazonLambdaAPIGatewayEvents>2.7.1</AmazonLambdaAPIGatewayEvents>
        <AWSLambdaPowertoolsLogging>1.6.5</AWSLambdaPowertoolsLogging>
        <AWSLambdaPowertoolsTracing>1.6.1</AWSLambdaPowertoolsTracing>
        <AWSLambdaPowertoolsMetrics>2.0.0</AWSLambdaPowertoolsMetrics>
        <AmazonLambdaAnnotations>1.7.0</AmazonLambdaAnnotations>
        <AWSSDKDynamoDBv2>3.7.406.17</AWSSDKDynamoDBv2>
        <AWSSDKApiGatewayManagementApi>3.7.400.129</AWSSDKApiGatewayManagementApi>
        <AWSSDKCognitoIdentityProvider>3.7.407.24</AWSSDKCognitoIdentityProvider>
        <AWSSDKVerifiedPermissions>3.7.402.43</AWSSDKVerifiedPermissions>
        <AWSSDKRekognition>3.7.400.129</AWSSDKRekognition>
        <AWSSDKS3>3.7.416.5</AWSSDKS3>
        <AWSSDKExtensionsNETCoreSetup>3.7.400</AWSSDKExtensionsNETCoreSetup>
        <Constructs>10.4.2</Constructs>
        <FakeItEasy>8.3.0</FakeItEasy>
        <FluentAssertions>8.2.0</FluentAssertions>
        <FluentValidationDependencyInjectionExtensions>11.8.1</FluentValidationDependencyInjectionExtensions>
        <MicrosoftNETTestSdk>17.13.0</MicrosoftNETTestSdk>
        <MicrosoftIdentityModelProtocolsOpenIdConnect>8.7.0</MicrosoftIdentityModelProtocolsOpenIdConnect>
        <MagickNETQ8AnyCPU>14.6.0</MagickNETQ8AnyCPU>
        <CoverletCollector>6.0.4</CoverletCollector>
        <JsonWebToken>1.9.4</JsonWebToken>
        <Xunit>2.9.0</Xunit>
        <XunitRunnerVisualstudio>2.8.2</XunitRunnerVisualstudio>
        <SystemIdentityModelTokensJwt>7.5.1</SystemIdentityModelTokensJwt>
    </PropertyGroup>
</Project>